site:
  title: "RHOSP Networking Break-fix Practice - Diagnosing Destination Host Unreachable and No Route to Host Errors"
  start_page: rhosp-bfx-019::index.adoc

content:
  sources:
  - url: ./

asciidoc:
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
