= Guided solution (page 2)

1. Capture ARP request packets using tcpdump.
+
----
[root@compute01 ~]# tcpdump -i eth2 arp -c1 -w arp-request.pcap
dropped privs to tcpdump
tcpdump: listening on eth2, link-type EN10MB (Ethernet), capture size 262144 bytes
1 packet captured
1 packet received by filter
0 packets dropped by kernel
----
+
Before running the above command, ensure to ping the floating IP from another terminal to generate the necessary packets.


2. Check if the captured packets are ARP requests for the floating IP.
+
----
[root@compute01 ~]# tcpdump -r arp-request.pcap
reading from file arp-request.pcap, link-type EN10MB (Ethernet), snapshot length 262144
dropped privs to tcpdump
10:35:47.429743 ARP, Request who-has 192.168.51.165 tell _gateway, length 28
----

3. Identify the OpenFlow protocol number for network interface ens3.
+
----
[root@compute01 ~]# ovs-ofctl show br-ex
OFPT_FEATURES_REPLY (xid=0x2): dpid:000052540002331f
n_tables:254, n_buffers:0
capabilities: FLOW_STATS TABLE_STATS PORT_STATS QUEUE_STATS ARP_MATCH_IP
actions: output enqueue set_vlan_vid set_vlan_pcp strip_vlan mod_dl_src mod_dl_dst mod_nw_src mod_nw_dst mod_nw_tos mod_tp_src mod_tp_dst
 1(eth2): addr:52:54:00:02:33:1f
     config:     0
     state:      0
     speed: 0 Mbps now, 0 Mbps max
 LOCAL(br-ex): addr:52:54:00:02:33:1f
     config:     0
     state:      0
     speed: 0 Mbps now, 0 Mbps max
OFPT_GET_CONFIG_REPLY (xid=0x4): frags=normal miss_send_len=0
----
+
[NOTE]
====
eth2 is associated with port number 1
====

4. Perform the OpenFlow protocol trace on br-ex with in_port set to 1.
+
----
[root@compute01 ~]# ovs-appctl ofproto/trace br-ex in_port=1 $(ovs-pcap arp-request.pcap)
Flow: in_port=1,vlan_tci=0x0000,dl_src=00:00:00:00:00:00,dl_dst=00:00:00:00:00:00,dl_type=0x0000

bridge("br-ex")
---------------
 0. priority 0
    NORMAL
     -> no learned MAC for destination, flooding

Final flow: unchanged
Megaflow: recirc_id=0,eth,in_port=1,dl_src=00:00:00:00:00:00,dl_dst=00:00:00:00:00:00,dl_type=0x0000
Datapath actions: 3
----

5. Analyze the trace output. In this case, the trace shows that the ARP request is flooding, and "Datapath actions: 3" indicates that it was delivered to br-ex (see output of below command).
+
----
[root@compute01 ~]# ovs-dpctl show
system@ovs-system:
  lookups: hit:28425 missed:2050 lost:0
  flows: 10
  masks: hit:46507 total:4 hit/pkt:1.53
  cache: hit:20808 hit-rate:68.28%
  caches:
    masks-cache: size:256
  port 0: ovs-system (internal)
  port 1: genev_sys_6081 (geneve: packet_type=ptap)
  port 2: br-int (internal)
  port 3: br-ex (internal)
  port 4: br-osp (internal)
  port 5: eth2
  port 6: eth3
  port 7: vlan20 (internal)
  port 8: vlan21 (internal)
  port 9: vlan22 (internal)
  port 10: tap3abe5cf3-3d
  port 11: tap1655a6ba-a0
----
+
[NOTE]
====
"Data path 3" means the traffic was delivered to br-ex, which is a port on the br-ex bridge.
====

6. Run tcpdump on br-ex.
+
----
[root@compute01 ~]# tcpdump -envvi br-ex arp
dropped privs to tcpdump
tcpdump: listening on br-ex, link-type EN10MB (Ethernet), snapshot length 262144 bytes
10:39:33.611718 52:54:00:02:33:fe > Broadcast, ethertype ARP (0x0806), length 42: Ethernet (len 6), IPv4 (len 4), Request who-has 192.168.51.165 tell 192.168.51.254, length 28
10:39:34.664540 52:54:00:02:33:fe > Broadcast, ethertype ARP (0x0806), length 42: Ethernet (len 6), IPv4 (len 4), Request who-has 192.168.51.165 tell 192.168.51.254, length 28
10:39:35.688557 52:54:00:02:33:fe > Broadcast, ethertype ARP (0x0806), length 42: Ethernet (len 6), IPv4 (len 4), Request who-has 192.168.51.165 tell 192.168.51.254, length 28
----
+
- The output shows ARP requests, indicating that the traffic is indeed being received by the br-ex port.

- However, the issue lies in why this traffic is not making its way to br-int, which is crucial for proper network routing.

- There is a floating IP configured on a particular compute node.

- OVN (Open Virtual Network) is aware of this configuration.

- OVN creates a patch port between the provider network and br-int. * Importantly, each provider network has its own patch port connecting br-ex and br-int.

7. Review at the ovs-vsctl show output captured earlier, br-ex has only one port - eth2, which is the NIC (Network Interface Card) of the compute node.
+
----
[root@compute01 ~]# ovs-vsctl show
. . .
    Bridge br-ex
        fail_mode: standalone
        Port eth2
            Interface eth2
        Port br-ex
            Interface br-ex
                type: internal

. . .
----
+
The key issue here is the absence of a patch port between br-int and br-ex. This missing link prevents traffic from flowing properly between the internal network (br-int) and the external network (br-ex).

8. Now let us examine your OVN bridge mappings.
+
----
[root@compute01 ~]# ovs-vsctl list open .
_uuid               : 54ee4d39-0f5f-4be7-9253-e7963bf0ec50
bridges             : [791bdbc0-dd86-4887-a8da-6a4ec607a78a, 87964f92-7b3f-4369-ae35-1fbdae989968, b70a83c6-601e-4bd4-aa4b-17eed47dd582]
cur_cfg             : 243
datapath_types      : [netdev, system]
datapaths           : {system=e0825819-b833-4f7a-af2b-a9c5d404be2a}
db_version          : "8.5.0"
dpdk_initialized    : false
dpdk_version        : "DPDK 23.11.0"
external_ids        : {hostname=compute01.srv.example.com, ovn-bridge=br-int, ovn-chassis-mac-mappings="datacentre:0e:0a:e5:24:00:67", ovn-cms-options=enable-chassis-as-gw, ovn-encap-ip="172.19.0.110", ovn-encap-tos="0", ovn-encap-type=geneve, ovn-match-northd-version=False, ovn-monitor-all=True, ovn-ofctrl-wait-before-clear="8000", ovn-remote="ssl:ovsdbserver-sb.openstack.svc:6642", ovn-remote-probe-interval="60000", rundir="/var/run/openvswitch", system-id="08d5cafe-22c0-4ea8-b026-908330a80389"}
iface_types         : [bareudp, erspan, geneve, gre, gtpu, internal, ip6erspan, ip6gre, lisp, patch, srv6, stt, system, tap, vxlan]
manager_options     : [71d44a22-8aae-4efa-a104-9fba5f38f795]
next_cfg            : 243
other_config        : {ovn-chassis-idx-08d5cafe-22c0-4ea8-b026-908330a80389="", vlan-limit="0"}
ovs_version         : "3.3.3-49.el9fdp"
ssl                 : []
statistics          : {}
system_type         : rhel
system_version      : "9.4"
----
+
[NOTE]
====
Bridge mappings are important for determining which provider network corresponds to a specific bridge.
====

9. This output shows the OVN setup, including bridges, data paths, and various configurations. Bridge mapping is stored in external_ids.
+
----
external_ids        : {hostname=compute01.srv.example.com, ovn-bridge=br-int, ovn-chassis-mac-mappings="datacentre:0e:0a:e5:24:00:67", ovn-cms-options=enable-chassis-as-gw, ovn-encap-ip="172.19.0.110", ovn-encap-tos="0", ovn-encap-type=geneve, ovn-match-northd-version=False, ovn-monitor-all=True, ovn-ofctrl-wait-before-clear="8000", ovn-remote="ssl:ovsdbserver-sb.openstack.svc:6642", ovn-remote-probe-interval="60000", rundir="/var/run/openvswitch", system-id="08d5cafe-22c0-4ea8-b026-908330a80389"}
iface_types         : [bareudp, erspan, geneve, gre, gtpu, internal, ip6erspan, ip6gre, lisp, patch, srv6, stt, system, tap, vxlan]
----
+
Notably, it lacks information about bridge mappings. Bridge mappings play an important role in associating a NIC with a provider network (commonly referred to as a datacenter network). In this case OVN does not know which provider network is the datacenter because it needs to map between the NIC and the provider network. To create this connection, we need to inform OVN about the relationship between the NIC and the provider network, typically named 'datacenter'.

10. Explore public network details.
+
----
[student@workstation ~]$ oc exec -n openstack openstackclient -- openstack network show public
+---------------------------+--------------------------------------+
| Field                     | Value                                |
+---------------------------+--------------------------------------+
| admin_state_up            | UP                                   |
| availability_zone_hints   |                                      |
| availability_zones        |                                      |
| created_at                | 2025-03-31T09:33:26Z                 |
| description               |                                      |
| dns_domain                |                                      |
| id                        | ee961465-e812-4563-aaa8-05adb3476889 |
| ipv4_address_scope        | None                                 |
| ipv6_address_scope        | None                                 |
| is_default                | False                                |
| is_vlan_transparent       | None                                 |
| l2_adjacency              | True                                 |
| mtu                       | 1500                                 |
| name                      | public                               |
| port_security_enabled     | True                                 |
| project_id                | 7ac1618d984947c0bfcbf713a94fed4a     |
| provider:network_type     | flat                                 |
| provider:physical_network | datacentre                           |
| provider:segmentation_id  | None                                 |
| qos_policy_id             | None                                 |
| revision_number           | 2                                    |
| router:external           | External                             |
| segments                  | None                                 |
| shared                    | False                                |
| status                    | ACTIVE                               |
| subnets                   | 3c99909a-9d7a-486a-9df5-6e3fb210df61 |
| tags                      |                                      |
| tenant_id                 | 7ac1618d984947c0bfcbf713a94fed4a     |
| updated_at                | 2025-03-31T09:33:30Z                 |
+---------------------------+--------------------------------------+
----
+
In this output, find information about the "public" network, including its physical network, which is labeled as "datacentre."
+
----
| provider:physical_network | datacentre
----
+
This is essentially a placeholder name that we define in configuration files. We need to specify which NIC on the compute nodes corresponds to this "datacenter" network.
+
[NOTE]
====
The issue at hand is that OVN does not inherently know that the br-ex` bridge represents the `datacenter`provider network.
====
+
To establish this link, we must explicitly configure OVN bridge mappings. This configuration ensures that OVN associates br-ex with the datacenter network.

11. Configure the OVN bridge mapping settings using the ovs-vsctl set command.
+
----
[root@compute01 ~]# ovs-vsctl set open . external_ids:ovn-bridge-mappings=datacentre:br-ex
----

12. Re-run the ovs-vsctl show command to verify that a patch port has been created between br-int and br-ex.
+
----
[root@compute01 ~]# ovs-vsctl show
. . .
    Bridge br-int
        fail_mode: secure
        datapath_type: system
. . .
		Port patch-br-int-to-provnet-84157851-395c-40eb-a3ec-6b512dd58759
            Interface patch-br-int-to-provnet-84157851-395c-40eb-a3ec-6b512dd58759
                type: patch
                options: {peer=patch-provnet-84157851-395c-40eb-a3ec-6b512dd58759-to-br-int}
. . .
    Bridge br-ex
        fail_mode: standalone
        Port patch-provnet-84157851-395c-40eb-a3ec-6b512dd58759-to-br-int
            Interface patch-provnet-84157851-395c-40eb-a3ec-6b512dd58759-to-br-int
                type: patch
                options: {peer=patch-br-int-to-provnet-84157851-395c-40eb-a3ec-6b512dd58759}
        Port eth2
            Interface eth2
        Port br-ex
            Interface br-ex
                type: internal
. . .
----
+
This connection is crucial for proper network communication. By addressing this missing link, we can ensure that traffic flows smoothly between the internal and external networks, thus resolving the connectivity issue we encountered.

13. Test ssh and ping again to ensure that both are now working.
+
----
[student@workstation roles]$ ping 192.168.51.165 -c 1
PING 192.168.51.165 (192.168.51.165) 56(84) bytes of data.
64 bytes from 192.168.51.165: icmp_seq=1 ttl=62 time=16.1 ms

--- 192.168.51.165 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 16.120/16.120/16.120/0.000 ms

[student@workstation ~]$ ssh -i /tmp/scenario-bfx026-key.pem cirros@192.168.51.165
Warning: Permanently added '192.168.51.165' (ECDSA) to the list of known hosts.
sign_and_send_pubkey: no mutual signature supported
cirros@192.168.51.165's password:
$ uname -r
5.3.0-26-generic
$exit
Connection to 192.168.51.165 closed.
----
+
Note that for DVR, bridge mappings are required on compute nodes to access the provider network (public). This would ensure connectivity to the floating IP.

== Evaluation

As the stack user on the director machine, use the lab command to grade your work. Correct any reported failures and rerun the command until successful.
----
[stack@director ~]$ lab grade bfx026
----

== Finish

Run the lab finish command to complete this exercise. This step is important to ensure that resources from previous exercises do not impact upcoming exercises.
----
[stack@director ~]$ lab finish bfx026
----
This concludes the section.
