= Guided solution (page 1)

. Log in to your lab environment on the **ROLE** platform.
. Break the environment if you have not done it and then step through the fix.
+
As the **student** user, run the lab start script on the **workstation** VM to reproduce the issue.
+
[source, bash]
----
cd /home/student/osp_training/scenarios_repo/
./lab start bfx026
----
+
.Sample output
----
[student@workstation scenarios_repo]$ ./lab start bfx026
Running start action against scenario bfx026
[WARNING]: Invalid characters were found in group names but not replaced, use
-vvvv to see details
Run the following command: 
ssh -i /tmp/scenario-bfx026-key.pem cirros@192.168.51.98
----
+
NOTE: The IP address in the displayed output may differ in your case.

. Run the ssh command from the previous lab command output and notice the Connection timed out error. Also run the ping command against instance IP.
+
[source, bash]
----
ssh -i /home/student/osp_training/.scenariobfx026/scenario-bfx026-key.pem cirros@instance.ip.in.your.lab
----
+
[source, bash]
----
ping instance.ip.in.your.lab -c 1
----
+
IMPORTANT: In the above commands **replace** the string *instance.ip.in.your.lab* with the **actual IP** address displayed in the output of the lab start script.
+
.Sample output
----
[student@workstation ~]$ ssh -i /tmp/scenario-bfx026-key.pem cirros@192.168.51.98
ssh: connect to host 192.168.51.98 port 22: No route to host
[student@workstation ~]$ 
[student@workstation ~]$ ping 192.168.51.98 -c 1
PING 192.168.51.98 (192.168.51.98) 56(84) bytes of data.
From 172.25.250.253 icmp_seq=1 Destination Host Unreachable

--- 192.168.51.98 ping statistics ---
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms

[student@workstation ~]$ 
----
+
**You observe that both ping and ssh attempts failed which indicates lack of connectivity.**
+
NOTE: Only the utility server has configured IP address which belongs to the same Layer 2 (L2) domain as the Floating IP associated to the VM.

. Establish an SSH connection to the utility VM, then verify ping connectivity and ARP resolution from there.
+
[source, bash]
----
ssh lab@utility
----
+
[source, bash]
----
ping 192.168.51.98 -c 1
----
+
.Sample output
----
[student@workstation ~]$ ssh lab@utility
Register this system with Red Hat Insights: insights-client --register
Create an account or view all your systems at https://red.ht/insights-dashboard
Last login: Tue Jun 17 02:02:33 2025 from 172.25.250.9
[lab@utility ~]$
[lab@utility ~]$ ping 192.168.51.98 -c 1
PING 192.168.51.98 (192.168.51.98) 56(84) bytes of data.
From 192.168.51.254 icmp_seq=1 Destination Host Unreachable

--- 192.168.51.98 ping statistics ---
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms
----

. Because the ping test failed, it is essential to double-check with ARP. 

. Only the **utility** server has L2 access to the OSP External Network, hence you have to check ARP on that server.
+
[source, bash]
----
ip neighbour | grep 192.168.51.98
----
+
.Sample output
----
[root@utility ~]# ip neighbour | grep 192.168.51.98
192.168.51.98 dev eth2 FAILED
----

. Identify the network interface on the **utility** vm which is in the same IP address range as that of OSP External network.
+
[source, bash]
----
ip address
----
+
.Sample output
----
. . . 
4: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:02:33:fe brd ff:ff:ff:ff:ff:ff
    altname enp0s5
    altname ens5
    inet 192.168.51.254/24 brd 192.168.51.255 scope global noprefixroute eth2
       valid_lft forever preferred_lft forever
    inet6 fe80::ae34:5b6d:c0af:8a10/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
. . . 
----

. Run tcpdump on **utility** vm in one terminal and open a new terminal and ping the IP of the instance from **wokstation**
+
[source, bash]
----
sudo tcpdump -envvi eth2 arp
----
+
.Sample output terminal 1
----
[lab@utility ~]$ sudo tcpdump -envvi eth2 arp
dropped privs to tcpdump
tcpdump: listening on eth2, link-type EN10MB (Ethernet), snapshot length 262144 bytes
03:51:55.835096 52:54:00:02:33:fe > Broadcast, ethertype ARP (0x0806), length 42: Ethernet (len 6), IPv4 (len 4), Request who-has 192.168.51.98 tell 192.168.51.254, length 28
03:51:56.841041 52:54:00:02:33:fe > Broadcast, ethertype ARP (0x0806), length 42: Ethernet (len 6), IPv4 (len 4), Request who-has 192.168.51.98 tell 192.168.51.254, length 28
03:51:57.865025 52:54:00:02:33:fe > Broadcast, ethertype ARP (0x0806), length 42: Ethernet (len 6), IPv4 (len 4), Request who-has 192.168.51.98 tell 192.168.51.254, length 28
----
+
.Sample output terminal 2
----
[lab@utility ~]$ ping 192.168.51.98 -c 3
PING 192.168.51.98 (192.168.51.98) 56(84) bytes of data.
From 192.168.51.254 icmp_seq=1 Destination Host Unreachable
From 192.168.51.254 icmp_seq=2 Destination Host Unreachable
From 192.168.51.254 icmp_seq=3 Destination Host Unreachable

--- 192.168.51.98 ping statistics ---
3 packets transmitted, 0 received, +3 errors, 100% packet loss, time 2030ms
----
+
**You observe that ARP requests are being sent, but no responses are being received.**

. On the **workstation** vm use the openstackclient pod and check where the VM is running.
+
[source, bash]
----
oc exec -n openstack openstackclient -- openstack server list --long -c Name -c Status -c Host
----
+
.Sample output
----
[student@workstation ~]$ oc exec -n openstack openstackclient -- openstack server list --long -c Name -c Status -c Host
+--------------------+--------+---------------------------+
| Name               | Status | Host                      |
+--------------------+--------+---------------------------+
| scenario-bfx026-vm | ACTIVE | compute01.srv.example.com |
+--------------------+--------+---------------------------+
[student@workstation ~]$ 
----
+
**In the above output you observe that it is compute01.srv.example.com. This may vary in your case**
+
[NOTE]
====
The RHOSP cluster is configured to operate with Distributed Virtual Routing (DVR) functionality. As the DVR is enabled, all Floating IPs are treated as DVR, directing traffic directly to the compute node's br-ex interface. This arrangement ensures that traffic bound for the floating IP bypasses the control node entirely.
====

. Login to the **compute** node where instance is running and run **ovs-vsctl show** command.
+
.Sample output
----
[student@workstation ~]$ ssh root@compute01.srv.example.com
Activate the web console with: systemctl enable --now cockpit.socket

Register this system with Red Hat Insights: insights-client --register
Create an account or view all your systems at https://red.ht/insights-dashboard
Last login: Tue Jun 17 10:48:42 2025 from 192.168.51.254
[root@compute01 ~]# 
[root@compute01 ~]# ovs-vsctl show
. . . 
    Bridge br-ex
        fail_mode: standalone
        Port br-ex
            Interface br-ex
                type: internal
        Port eth2
            Interface eth2
. . . 
----
+
**Identify the network interface used under external bridge br-ex.**

. Verify the ARP requests on the Ethernet device eth2 used under br-ex.
+
**Run tcpdump on the compute node**
+
[source, bash]
----
tcpdump -envvi eth2 arp
----
+
**Run ping from the utility vm**
+
[source, bash]
----
ping IP -c 3
----
**Replace IP with appropriate string**
+
.Sample output terminal 1
----
[root@compute01 ~]# tcpdump -envvi eth2 arp
dropped privs to tcpdump
tcpdump: listening on eth2, link-type EN10MB (Ethernet), snapshot length 262144 bytes
08:03:47.363832 52:54:00:02:33:fe > Broadcast, ethertype ARP (0x0806), length 42: Ethernet (len 6), IPv4 (len 4), Request who-has 192.168.51.98 tell 192.168.51.254, length 28
08:03:48.394094 52:54:00:02:33:fe > Broadcast, ethertype ARP (0x0806), length 42: Ethernet (len 6), IPv4 (len 4), Request who-has 192.168.51.98 tell 192.168.51.254, length 28
08:03:49.418039 52:54:00:02:33:fe > Broadcast, ethertype ARP (0x0806), length 42: Ethernet (len 6), IPv4 (len 4), Request who-has 192.168.51.98 tell 192.168.51.254, length 28

----
+
.Sample output terminal 2
----
[lab@utility ~]$ ping 192.168.51.98 -c 3
PING 192.168.51.98 (192.168.51.98) 56(84) bytes of data.
From 192.168.51.254 icmp_seq=1 Destination Host Unreachable
From 192.168.51.254 icmp_seq=2 Destination Host Unreachable
From 192.168.51.254 icmp_seq=3 Destination Host Unreachable

--- 192.168.51.98 ping statistics ---
3 packets transmitted, 0 received, +3 errors, 100% packet loss, time 2055ms
----
+
- ARP requests are being sent but not replied.
- These should be answered by the router gateway port.
- The next step is to verify the connectivity from the Metadata namespace by attempting to ping the instance with its fixed IP.

. List the floating IP and ensure its alignment with the fixed IP address.
+
[source, bash]
----
oc exec -n openstack openstackclient -- openstack floating ip list
----
+
.Sample output
----
[student@workstation ~]$ oc exec -n openstack openstackclient -- openstack floating ip list
+--------------------------------------+---------------------+------------------+--------------------------------------+--------------------------------------+----------------------------------+
| ID                                   | Floating IP Address | Fixed IP Address | Port                                 | Floating Network                     | Project                          |
+--------------------------------------+---------------------+------------------+--------------------------------------+--------------------------------------+----------------------------------+
| 13261cca-3b7a-4229-9c63-aa3d49a0c110 | 192.168.51.98       | 192.168.190.127  | d2db5833-99bd-4de0-a7ca-bf8c1321882c | 5526bfcf-a164-4a91-ad99-90bb5c41f500 | d388b58059514443a8dced8c2ed691f6 |
+--------------------------------------+---------------------+------------------+--------------------------------------+--------------------------------------+----------------------------------+
[student@workstation ~]$ 
----

. Connect to the metadata namespace and ping to instance's fixed IP address from there.

. Run the following command on the **compute** node.
+
----
ip netns
ip netns exec <namespace> ping <fixed ip of instance> -c 1
----
+
**Replace <namespace> and <fixed ip of instance> with the appropriate string from the previous output.**
+
.Sample output
----
[root@compute01 ~]# ip netns
ovnmeta-96cd71b0-2988-43ca-bfd3-b3a9ddc59d51 (id: 0)
[root@compute01 ~]# 
[root@compute01 ~]# ip netns exec ovnmeta-96cd71b0-2988-43ca-bfd3-b3a9ddc59d51 ping 192.168.190.127 -c 1
PING 192.168.190.127 (192.168.190.127) 56(84) bytes of data.
64 bytes from 192.168.190.127: icmp_seq=1 ttl=64 time=0.543 ms

--- 192.168.190.127 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.543/0.543/0.543/0.000 ms
[root@compute01 ~]# 
----
+
**If you receive a response, it indicates that the VM's local network is functioning properly.**
+
[NOTE]
====
Connectivity works for ICMP from the namespace, which is local to the compute node, but it does not work from the outside. We can try running the OpenFlow protocol trace.
====
