= Guided solution (page 1)

== Objectives
* Investigate the instance connectivity issue in Red Hat OpenStack Platform.
* Solve the instance connectivity in the hands-on lab environment.

== Outcomes
* Investigate why ssh to instance is not working.
* Fix the ssh to instance failing issue.

== Instructions

1. Break the environment if you have not done it and step through the fix.
+
----
[student@workstation ~]$ lab start bfx026
Running break action against scenario bfx026
Run the following command:
ssh -i /tmp/scenario-bfx026-key.pem cirros@192.168.51.165
----

2. Run the ssh command from the previous lab command output and notice the No route to host error. Also run the ping command against instance IP.
+
----
[student@workstation ~]$ ssh -i /tmp/scenario-bfx026-key.pem cirros@192.168.51.165
ssh: connect to host 192.168.51.165 port 22: No route to host

[student@workstation ~]$ ping 192.168.51.165 -c 1
PING 192.168.51.165 (192.168.51.165) 56(84) bytes of data.
From 172.25.250.253 icmp_seq=1 Destination Host Unreachable

--- 192.168.51.165 ping statistics ---
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms
----
+
You observe that both ssh and ping attempts failed which indicates lack of connectivity.

3. Because the ping test failed, it is essential to double-check with ARP. Open run tcpdump on one terminal and open a new terminal and ping the IP of the instance.
+
Due to the fact that only the `utility` server has L2 access to the OSP External Network, you have to check ARP on that server.
----
[student@workstation ~]$ ssh lab@utility
Register this system with Red Hat Insights: insights-client --register
Create an account or view all your systems at https://red.ht/insights-dashboard
Last login: Mon Mar 31 06:27:54 2025 from 172.25.250.9
[lab@utility ~]$ sudo -i
[root@utility ~]# ip neighbour | grep 192.168.51.165
192.168.51.165 dev eth2 FAILED

[root@utility ~]# tcpdump -envvi eth2 | grep 192.168.51.165
dropped privs to tcpdump
tcpdump: listening on eth2, link-type EN10MB (Ethernet), snapshot length 262144 bytes
06:16:50.625686 52:54:00:02:33:fe > Broadcast, ethertype ARP (0x0806), length 42: Ethernet (len 6), IPv4 (len 4), Request who-has 192.168.51.165 tell 192.168.51.254, length 28
06:16:51.656605 52:54:00:02:33:fe > Broadcast, ethertype ARP (0x0806), length 42: Ethernet (len 6), IPv4 (len 4), Request who-has 192.168.51.165 tell 192.168.51.254, length 28
06:16:52.680579 52:54:00:02:33:fe > Broadcast, ethertype ARP (0x0806), length 42: Ethernet (len 6), IPv4 (len 4), Request who-has 192.168.51.165 tell 192.168.51.254, length 28
----
+
You observe that ARP requests are being sent, but no responses are being received.

4. Use openstackclient POD and check where the VM is running.
+
----
[student@workstation ~]$ oc exec -n openstack openstackclient -- openstack server list --long
+--------------------------------------+--------------------+--------+------------+-------------+---------------------------------------------------------+---------------------+--------------------------------------+----------+-------------------+---------------------------+------------+-------------+
| ID                                   | Name               | Status | Task State | Power State | Networks                                                | Image Name          | Image ID                             | Flavor   | Availability Zone | Host                      | Properties | Host Status |
+--------------------------------------+--------------------+--------+------------+-------------+---------------------------------------------------------+---------------------+--------------------------------------+----------+-------------------+---------------------------+------------+-------------+
| 410602ae-a400-4358-9723-312c493e409f | scenario-bfx026-vm | ACTIVE | None       | Running     | scenario-bfx026-network=192.168.190.187, 192.168.51.165 | cirros-0.5.2-x86_64 | 10210206-c30a-4765-8547-0dad335b5675 | m1.small | nova              | compute01.srv.example.com |            | UP          |
+--------------------------------------+--------------------+--------+------------+-------------+---------------------------------------------------------+---------------------+--------------------------------------+----------+-------------------+---------------------------+------------+-------------+
----
+
You observe that it is compute01.srv.example.com.
+
[NOTE]
====
The RHOSP cluster is configured to operate with Distributed Virtual Routing (DVR) functionality. As the DVR is enabled, all Floating IPs are treated as DVR, directing traffic directly to the compute node's br-ex interface. This arrangement ensures that traffic bound for the floating IP bypasses the control node entirely.
====

5. Identify the network interface used under external bridge br-ex.
+
----
[student@workstation ~]$ ssh root@compute01.srv.example.com
Activate the web console with: systemctl enable --now cockpit.socket

Register this system with Red Hat Insights: insights-client --register
Create an account or view all your systems at https://red.ht/insights-dashboard
Last login: Wed Apr  2 09:58:41 2025 from 192.168.51.254

[root@compute01 ~]# ovs-vsctl show
...
    Bridge br-ex
        fail_mode: standalone
        Port br-ex
            Interface br-ex
                type: internal
        Port eth2
            Interface eth2
...
----

6. Verify the ARP requests on the Ethernet device ens4 used under br-ex.
+
----
[root@compute01 ~]# tcpdump -envvi eth2 arp
dropped privs to tcpdump
tcpdump: listening on eth2, link-type EN10MB (Ethernet), snapshot length 262144 bytes
10:32:30.176581 52:54:00:02:33:fe > Broadcast, ethertype ARP (0x0806), length 42: Ethernet (len 6), IPv4 (len 4), Request who-has 192.168.51.165 tell 192.168.51.254, length 28
10:32:31.176926 52:54:00:02:33:fe > Broadcast, ethertype ARP (0x0806), length 42: Ethernet (len 6), IPv4 (len 4), Request who-has 192.168.51.165 tell 192.168.51.254, length 28
10:32:32.200834 52:54:00:02:33:fe > Broadcast, ethertype ARP (0x0806), length 42: Ethernet (len 6), IPv4 (len 4), Request who-has 192.168.51.165 tell 192.168.51.254, length 28
^C
3 packets captured
3 packets received by filter
0 packets dropped by kernel
----
+
- ARP requests are being sent but not replied.

- These should be answered by the router gateway port.

- The next step is to verify the connectivity from the Metadata namespace by attempting to ping the instance with its fixed IP.

7. List the floating IP and ensure its alignment with the fixed IP address.
+
----
[student@workstation ~]$ oc exec -n openstack openstackclient -- openstack floating ip list
+--------------------------------------+---------------------+------------------+--------------------------------------+--------------------------------------+----------------------------------+
| ID                                   | Floating IP Address | Fixed IP Address | Port                                 | Floating Network                     | Project                          |
+--------------------------------------+---------------------+------------------+--------------------------------------+--------------------------------------+----------------------------------+
| 5a1eb6f3-d643-4169-8deb-e6b2042d9c19 | 192.168.51.165      | 192.168.190.187  | 3abe5cf3-3d40-4c02-af97-59946cfd3951 | ee961465-e812-4563-aaa8-05adb3476889 | 7ac1618d984947c0bfcbf713a94fed4a |
+--------------------------------------+---------------------+------------------+--------------------------------------+--------------------------------------+----------------------------------+
----

8. Connect to the metadata namespace and ping to instance's fixed IP address from there. Run the following command on the compute node.
+
----
[root@compute01 ~]# ip netns
ovnmeta-1655a6ba-a91e-4d79-9e2f-ba6d44807c2a (id: 0)

[root@compute01 ~]# ip netns exec ovnmeta-1655a6ba-a91e-4d79-9e2f-ba6d44807c2a ping 192.168.190.187 -c 1
PING 192.168.190.187 (192.168.190.187) 56(84) bytes of data.
64 bytes from 192.168.190.187: icmp_seq=1 ttl=64 time=1.43 ms

--- 192.168.190.187 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 1.425/1.425/1.425/0.000 ms
----
+
If you get a response, it means that the VM's network is functioning correctly locally.
+
[NOTE]
====
Connectivity works for ICMP from the namespace, which is local to the compute node, but it does not work from the outside. We can try running the OpenFlow protocol trace.
====

9. Install the openvswitch-test packages if not already installed.
